### ISSUE TITLE
Idea: make it possible to Upgrade game type for an existing game

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#103]
Idea: could it be made possible to 'upgrade' your game type, if you decide to make your interactive story even more interactive ;) So after writing it you decide you need some actions / rules after all. Maybe add the necessary files, maybe copy the existing files into a new game of the correct type. Either approach would be fine.
Also add instructions to manual when this is possible.

**Comment by RutgerSchurgers** [comment]
I started aligning the two types of games. Now, they differ in:
Configuration of the rules, which can be easily changed
Styling, which can be easily changed
using .ts files. We should discuss whether not using these in the basic mode is worth it. It makes it simpler to start, but more confusing to move to a full game.

**Comment by RutgerSchurgers** [comment]
We discussed we probably get the best solution creating a task that can generate a location for the user so he doesn't have to add all the files and contents manually. Then we can remove the mode not using ts files.

**Comment by RutgerSchurgers** [comment]
I added a task to create a location. I'll recreate the interactive story and rewrite this part of the tutorial.

**Comment by RutgerSchurgers** [comment]
I updated the tutorial.
