### ISSUE TITLE
Tutorial screenshot incorrect

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#104]
Where it tells you how to start an adventuregame, there is a screenshot. The screen shown indeed loads when you first build an empty game, but if you press 'Start over' as the text instructs, the lay-out changes. This makes either the text or the screenshot incorrect. I suggest changing one of them (your preference). Or add the second screenshot and slightly change the text.
NB: this is no error or bug, it works fine, the tutorial is a bit confusing though.

**Comment by RutgerSchurgers** [comment]
This should be fixed now that I determine what to display in a better way.
