### ISSUE TITLE
Text when combining features is in the wrong order

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#114]
I assume it's just the text, not the action itself. Example:

Use trees on animals: You Use the animals on the trees. Nothing happens.

While you're looking at this, is it possible to remove hte capitalization on the second 'Use' here? 

In fact perhaps that whole second sentence is redundant and can be left out?

**Comment by RutgerSchurgers** [comment]
The order was wrong determining the outcome text. That's fixed now.
