### ISSUE TITLE
New feature: make items groupable

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#116]
Some items are not unique, like 'food' or 'wood'. I'd like to be able to stack these in the backpack, other containers, traders and on the ground (and any places I might forget), so it doesn't say "food, food, food, etc.", but instead "3 food", or "food x3". 
It's fine if a single non-unique item becomes '1 food'.

**Comment by RutgerSchurgers** [comment]
It is now possible to group items and split an item group. I implemented this for Veils of Verdandi in which you can use a pair of daggers. It can be improved when there are additional use-cases.
