### ISSUE TITLE
RemoveTarget doesn't always find the target to remove

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#117]
For example if it's in your backpack, it doesn't get removed and there are more locations.  Example in my game is the item 'food', wich has the action inside itself that it gets removed ('removeTarget') when you EAT it, but it stays in the backpack instead.

**Comment by RutgerSchurgers** [comment]
I added code to remove the target and tool from all supported feature locations. It still needs to be tested.

**Comment by RutgerSchurgers** [comment]
I tested it with the eat example and it now works.
