### ISSUE TITLE
Tell me more about items and what they can do

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#118]
Could you expand the tutorial chapter on Items? WHat must be in an item, why, how do you add combinations to them, can you add actions to them and how does that work? How do they interact with rules, character and other areas?

Example: say, I have a magical scroll that I can use to brightly light a room, but only if my intelligence is high enough. Or a ring that increases charisma and also lets me shoot fireballs as an action (maybe at a price? or only once a day?). Could a trader have a dagger with a random magical property that also changes the price? Etc.

**Comment by RutgerSchurgers** [comment]
Made part of updating the tutorial: https://github.com/StrixIT/StoryScript/issues/113.
