### ISSUE TITLE
For user friendliness, could you add snippets?

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#119]
To make it easier tostart an item, action, destination, etc. add a simple way to create an empty version of these things, so I don't have to copy paste them. Alternatively, a place (a file?) where empty versions of all of these can be easily found and copy/pasted, with some hints about how to fill them and some explanation of why and troubleshooting if things don't work.

**Comment by RutgerSchurgers** [comment]
Snippets are now available for most entities. I still need to add them for features and quests. You should be able to use them by copying the file StoryScriptSnippets.code-snippets from the CodeSnippets directory to the .vscode directory. Type ss to show the available snippets using intellisense.

**Comment by RutgerSchurgers** [comment]
I added snippets for features, inline features and quests. Also, for snippets creating a named function, the name property is now set using the same name.

**Comment by RutgerSchurgers** [comment]
Snippets are now available for most entities. I still need to add them for features and quests. You should be able to use them by copying the file StoryScriptSnippets.code-snippets from the CodeSnippets directory to the .vscode directory. Type ss to show the available snippets using intellisense.

**Comment by RutgerSchurgers** [comment]
I now also added snippets for html files and added tab order for the snippets to make them work even better. This is a huge time saver!

**Comment by RutgerSchurgers** [comment]
I added a tutorial to explain how to use the snippets at https://github.com/StrixIT/StoryScript/wiki/Getting-started. I'll close this issue now.
