### ISSUE TITLE
Published game doesn't work in Edge

### ISSUE THREAD

**Issue by Fasoldgames** [StrixIT/StoryScript#120]
Publish a small game with just two locations. Edge doesn't show anything but curly brackets:
![afbeelding](https://user-images.githubusercontent.com/19929463/63580498-416d6c80-c595-11e9-8ac8-f611298f277d.png)

**Comment by Fasoldgames** [comment]
Branch: LanternOfWorlds.

**Comment by RutgerSchurgers** [comment]
Apparently, this is a bug in Edge for local files. It is not an issue when developing nor when hosting them in a web-server. Nothing I can do to fix it, and apparently nothing Microsoft is going to do about it, The bug report is from 2016 (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8816771/)! I'll note this as a known issue.
