### ISSUE TITLE
Edit required to Tutorial

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#171]
For the first step in the tutorial, installing nodejs. This install process asks the question below:
![image](https://user-images.githubusercontent.com/14853029/203588660-40b69cab-5251-45b2-b842-303e86dbc522.png)
(Whether you want to install extra tools, including 'Chocolatey');  the answer is this is not necessary, you can skip this step.

Secondly, the 'git: clone' option can be missing without showing an error (in that case you still need to istall Git for windows).

**Comment by RutgerSchurgers** [comment]
Fixed on master
