### ISSUE TITLE
Tutorial edit #2

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#172]
The tutorial on page 5 advises to copy the code snippets to the .vscode folder. However, this folder does not automatically exist. In that case, you should add a folder with that exact name and then paste the codesnippets in. The other files shown in the screenshot are not relevant. Below the resulting situation, which is correct:
![image](https://user-images.githubusercontent.com/14853029/203594115-db4fceda-fe51-43b5-8273-0fb8777e2fd1.png)

**Comment by RutgerSchurgers** [comment]
Fixed on master
