### ISSUE TITLE
Move item descriptions to separate html file

### ISSUE THREAD

**Issue by RutgerSchurgers** [StrixIT/StoryScript#31]
Now that we have support for html descriptions, move the description texts from the .ts files to .html files for DangerousCave and RidderMagnus.

**Comment by Cassanne** [comment]
Ik snap geloof ik niet helemaal wat je bedoelt - de logtolocation stukjes? Even overleggen?

**Comment by RutgerSchurgers** [comment]
I made using a html description optional. You can use it if you want to by using a constant as the description value. Other description values are used as plain text.
