### ISSUE TITLE
Vertaling specifieke term

### ISSUE THREAD

**Issue by Cassanne** [StrixIT/StoryScript#77]
Ik wil 'Defense' vertalen (naar een nederlands woord), maar hier zit waarschijnlijk een andere term achter? Of het is spel-specifiek?
Hoe krijg ik het voor elkaar?

**Comment by RutgerSchurgers** [comment]
De 'defense' eigenschap van het personage werd nog niet gebruikt in het berekenen van bonussen. Dat heb ik aangepast. Verder is het is een spel-specifieke term. Je kunt wel standaard-teksten vervangen, maar er is (nog) geen mechanisme om eigen termen te vertalen. Dat wordt pas nuttig als je een spel wilt vertalen in meerdere talen. Dat lijkt me nog niet zo belangrijk.

Voor nu kun je defense gewoon veranderen in een term in het Nederlands (je kunt gemakkelijk vinden in VS Code waar de term gebruikt wordt). De andere spel-specifieke eigenschappen (die in de UI getoond worden, er bestaat ook 'attack') zijn al in het Nederlands.
